[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = false
runs = 100
viaIR = false

[profile.prod]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
runs = 100
viaIR = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config